/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
      screens: {
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      }
    ,extend: {
      colors: {
        "text-primary": "#000",
        "border-alternate": "#fff",
        "border-default-default": "#d9d9d9",
        "text-default-secondary": "#757575",
        "text-default-default": "#1e1e1e",
        "pagination-colortext": "rgba(0, 0, 0, 0.88)",
        "pagination-colorprimary": "#3d91b2",
        "table-colorsplit": "rgba(0, 0, 0, 0.06)",
        "blue-1": "#e6f4ff",
        "blue-3": "#91caff",
        "blue-6": "#1677ff",
        "green-1": "#f6ffed",
        "green-3": "#b7eb8f",
        "green-6": "#52c41a",
        "table-colorfillalter": "rgba(0, 0, 0, 0.02)",
        "breadcrumb-colortextdescription": "rgba(0, 0, 0, 0.45)",
        colormenudarkbg: "#203033",
        coloritemtext: "rgba(255, 255, 255, 0.65)",
        "menu-colormenusubitembg": "#132224",
        "menu-colormenuthirditembg": "#081617",
        "menu-colorsecondaryactive": "#9ac258",
        "menu-colorheadermenubg": "#0d759f",
        "orange-1": "#fff7e6",
        "orange-6": "#fa8c16",
        whitesmoke: "#f4f4f4",
        colortextsecondary: "rgba(0, 0, 0, 0.65)",
        colorfill: "rgba(0, 0, 0, 0.15)",
        "table-colortextdisabled": "rgba(0, 0, 0, 0.25)",
        "border-alternate": "#fff",
        steelblue: "#669bbc",
        darkslategray: "#003049",
        chocolate: {
          "100": "#e96e0a",
          "200": "rgba(248, 145, 61, 0.3)",
        },
        "color-neutral-black": "#000",
      },
      spacing: {
        "space-200": "8px",
        "space-400": "16px",
        "space-300": "12px",
        "space-100": "4px",
        "padding-lg": "16px",
        "padding-sm": "8px",
        "pagination-marginxs": "8px",
        "table-padding": "16px",
        "pagination-controlheight": "32px",
        "table-margin": "16px",
        "button-paddingxs": "8px",
        "button-marginxs": "8px",
        "button-controlheight": "32px",
        "table-paddingxs": "8px",
        "table-paddingcontentverticallg": "16px",
        "checkbox-marginxs": "8px",
        "button-paddingcontenthorizontal": "16px",
        "tabs-paddingsm": "12px",
        "breadcrumb-paddingxxs": "4px",
        "breadcrumb-marginxxs": "4px",
        "menu-sidermenuwidth": "264px",
        "menu-marginxxs": "4px",
        "menu-paddingxs": "8px",
        "menu-marginsm": "12px",
        "menu-paddingright52": "52px",
        "menu-paddinglg": "24px",
        "menu-padding": "16px",
        sidemenuwidth: "264px",
        "menu-paddingleft60": "60px",
        "menu-paddingsm": "12px",
        padding: "16px",
        "menu-margin": "16px",
        controlheightsm: "24px",
        paddingxs: "8px",
        marginxs: "8px",
        marginxl: "32px",
        paddingxxl: "48px",
        paddingxl: "32px",
        marginxxs: "4px",
        "select-controlheightlg": "40px",
      },
      fontFamily: {
        roboto: "Roboto",
        "heading-desktop-h5": "SUSE",
        "single-line-body-base": "Inter",
        "heading-heading-3": "'Noto Sans TC'",
        "light-lg-lg-normal": "'SF Pro Text'",
      },
      borderRadius: {
        xl: "20px",
        "31xl": "50px",
        "26xl": "45px",
        "3xs": "10px",
        "radius-200": "8px",
        "radius-md": "8px",
        "pagination-borderradius": "6px",
        "button-borderradius": "6px",
        "tag-borderradiussm": "4px",
        "breadcrumb-borderradiussm": "4px",
        "button-borderradiuslg": "8px",
        "input-borderradiuslg": "8px",
        "select-borderradius": "6px",
      },
      screens: {
        'xsm' : '520px',
        'ism' : '400px',
        'xxsm' : '330px',
      },
      /*backgroundImage: {
        'home-page': "url('/Frame_3.png')",
      }*/
    },
    fontSize: {
      base: "16px",
      "5xl": "24px",
      "16xl": "35px",
      "51xl": "70px",
      "91xl": "110px",
      "21xl": "40px",
      "13xl": "32px",
      lg: "18px",
      "29xl": "48px",
      "37xl": "56px",
      sm: "14px",
      xs: "12px",
      "11xl": "30px",
      inherit: "inherit",
    },
  },
  corePlugins: {
    preflight: false,
  },
  
};
